name: Bump release version and build-push image

on:
  push:
    branches:
      - release4
env:
  NODE_VERSION: 20.x
  RELEASE_BRANCH: release4

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    outputs:
      new_tag: ${{ steps.release_version.outputs.tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}

    steps:
      - uses: actions/checkout@v4

      - name: print current branch
        run: |
          echo "Current branch is ${{ github.ref }}"
          echo "Current commit is ${{ github.sha }}"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      ## Commit message examples for Release type (patch|minor|major) can be found: 11111
      ## https://github.com/mathieudutour/github-tag-action
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: ${{ env.RELEASE_BRANCH }}

      - name: Strip 'v' from the tag
        id: release_version
        run: |
          TAG=${{ steps.tag_version.outputs.new_tag }}
          WITHOUT_V=${TAG#v}
          echo "tag=$WITHOUT_V" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/scicatproject/frontend
          tags: |
            type=raw,value=stable
            type=raw,value=${{ steps.tag_version.outputs.new_tag }}
            type=semver,pattern={{version}}
            type=raw,value={{date 'YYYY_MM'}},prefix=r_

      - name: update npm version
        run: npm version --no-git-tag-version ${{ steps.release_version.outputs.tag }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
